
Event.destroy_all
Ticket.destroy_all
User.destroy_all

user1 = User.create(username: "Sam", password: "1234")
user2 = User.create(username: "Rak", password: "4321")
user3 = User.create(username: "Islam", password: "1111")
user4 = User.create(username: "Derick", password: "2222")
user5 = User.create(username: "Max", password: "3333")



event1 = Event.create(event_name: "Superbowl XCII", category: "Sporting Event", city: "Chicago", location: "Outdoor", date: "11-15-2020")
event2 = Event.create(event_name: "Blink 182", category: "Music", city: "Chicago", location: "Outdoor", date: "11-15-2020")
event3 = Event.create(event_name: "Miami Heat vs Chicago Bulls", category: "Sporting Event", city: "Miami", location: "Indoor", date: "11-15-2020")
event4 = Event.create(event_name: "Drake", category: "Music", city: "Chicago", location: "Indoor", date: "11-15-2020")
event5 = Event.create(event_name: "Chicago Fire vs Portland Timbers", category: "Sporting Event", city: "Chicago", location: "Outdoor", date: "11-15-2020")
event6 = Event.create(event_name: "Bill Burr: LIVE", category: "Theater", city: "Los Angeles", location: "Indoor", date: "11-15-2020")
event7 = Event.create(event_name: "Phantom of the Opera", category: "Theater", city: "Chicago", location: "Indoor", date: "11-15-2020")
event8 = Event.create(event_name: "Los Angeles Lakers vs Chicago Bulls", category: "Sporting Event", city: "Los Angeles", location: "Indoor", date: "11-15-2020")
event9 = Event.create(event_name: "Dave Chapelle", category: "Theater", city: "Chicago", location: "Indoor", date: "11-15-2020")
event10 = Event.create(event_name: "Las Angeles Dodges vs Houston Cheaters", category: "Sporting Event", city: "Los Angeles", location: "Outdoor", date: "11-15-2020")
event11 = Event.create(event_name: "Detroit Pistons vs Another Trash Team", category: "Sporting Event", city: "Detroit", location: "Indoor", date: "11-15-2020")
event12 = Event.create(event_name: "Red Hot Chili Peppers", category: "Music", city: "Milwaukee", location: "Outdoor", date: "11-15-2020")
event13 = Event.create(event_name: "Milwaukee Bucks vs LA Clippers", category: "Sporting Event", city: "Milwaukee", location: "Indoor", date: "11-15-2020")
event14 = Event.create(event_name: "Hamilton", category: "Theater", city: "New York", location: "Indoor", date: "11-15-2020")
event15 = Event.create(event_name: "New York Knicks vs Brooklyn Nets", category: "Sporting Event", city: "New York", location: "Indoor", date: "11-21-2020")
event16 = Event.create(event_name: "Post Malone", category: "Music", city: "New York", location: "Outdoor", date: "11-21-2020")
event17 = Event.create(event_name: "Wicked", category: "Theatre", city: "Chicago", location: "Indoor", date: "11-21-2020")
event18 = Event.create(event_name: "Kanye West", category: "Music", city: "Chicago", location: "Outdoor", date: "11-21-2020")
event19 = Event.create(event_name: "Boston Bruins vs Pittsburgh Penguins", category: "Sporting Event", city: "Boston", location: "Outdoor", date: "01-01-2021")
event20 = Event.create(event_name: "Beyonce", category: "Music", city: "Boston", location: "Outdoor", date: "11-21-2020")
event21 = Event.create(event_name: "The Nutcracker", category: "Theater", city: "Boston", location: "Indoor", date: "11-21-2020")
event22 = Event.create(event_name: "Houston Rockets vs Chicago Bulls", category: "Sporting Eevent", city: "Houston", location: "Indoor", date: "11-21-2020")
event22 = Event.create(event_name: "Luke Combs", category: "Music", city: "Houston", location: "Outdoor", date: "11-21-2020")
event23 = Event.create(event_name: "The Kardashians: LIVE! ", category: "Theater", city: "Houston", location: "Indoor", date: "11-21-2020")
event24 = Event.create(event_name: "Ariana Grande", category: "Music", city: "Milwaukee", location: "Outdoor", date: "11-21-2020")
event25 = Event.create(event_name: "San Diego Padres vs San Francisco Giants", category: "Sporting Event", city: "San Diego", location: "Outdoor", date: "11-21-2020")
event26 = Event.create(event_name: "Emotional Oranges", category: "Music", city: "San Diego", location: "Outdoor", date: "11-21-2020")
event27 = Event.create(event_name: "The Lion King: LIVE!", category: "Theater", city: "San Diego", location: "Outdoor", date: "11-21-2020")
event28 = Event.create(event_name: "Seattle Seahawks vs The Dallas Cowboys", category: "Sporting Event", city: "Seattle", location: "Outdoor", date: "11-21-2020")
event29 = Event.create(event_name: "Destiny's Child: The Reunion", category: "Music", city: "Seattle", location: "Outdoor", date: "11-21-2020")
event30 = Event.create(event_name: "Chicago Bulls vs Milwaukee Bucks", category: "Sporting Event", city: "Chicago", location: "Indoor", date: "12-25-2020")
event31 = Event.create(event_name: "Seattle Seahawks vs San Francisco 49ers", category: "Sporting Event", city: "Seattle", location: "Outdoor", date: "11-29-2020")
event32 = Event.create(event_name: "Los Angeles Rams vs Los Angeles Charges", category: "Sporting Event", city: "Los Angeles", location: "Ourdoor", date: "11-29-2020")
event33 = Event.create(event_name: "Boston Celtics vs Miami Heat", category: "Sporting Event", city: "Boston", location: "Indoor", date: "12-25-2020")
event34 = Event.create(event_name: "Detroit Red Wings vs Chicago Blackhawks", category: "Sporting Event", city: "Detroit", location: "Indoor", date: "12-19-2020")
event35 = Event.create(event_name: "Detroit Lions vs Chicago Bears", category: "Sporting Event", city: "Detroit", location: "Indoor", date: "11-26-2020")
event36 = Event.create(event_name: "Miami Heat vs Los Angeles Lakers", category: "Sporting Event", city: "Miami", location: "Indoor", date: "01-02-2020")
event37 = Event.create(event_name: "New York Jets vs Washington Football Team", category: "Sporting Event", city: "New York", location: "Outdoor", date: "11-29-2020")
event38 = Event.create(event_name: "New York Giants vs Baltimore Ravens", category: "Sporting Event", city: "New York", location: "Outdoor", date: "12-06-2020")
event39 = Event.create(event_name: "New York Knicks vs Chicago Bulls", category: "Theater", city: "Seattle", location: "Indoor", date: "01-02-2020")
event40 = Event.create(event_name: "New York Knicks vs Portland Trailblazers", category: "Sporting Event", city: "New York", location: "Indoor", date: "01-09-2020")
event41 = Event.create(event_name: "Maroon 5", category: "Music", city: "Chicago", location: "Outdoor", date: "11-28-2020")
event42 = Event.create(event_name: "Kid Rock", category: "Music", city: "Detroit", location: "Outdoor", date: "11-28-2020")
event43 = Event.create(event_name: "Bad Bunny", category: "Music", city: "Los Angeles", location: "Outdoor", date: "11-28-2020")
event44 = Event.create(event_name: "Blake Shelton", category: "Music", city: "Houston", location: "Outdoor", date: "11-29-2020")
event45 = Event.create(event_name: "Boston", category: "Music", city: "Boston", location: "Outdoor", date: "11-29-2020")
event46 = Event.create(event_name: "Lil Baby", category: "Music", city: "Milwaukee", location: "Indoor", date: "11-29-2020")
event47 = Event.create(event_name: "Nas", category: "Music", city: "New York", location: "Outdoor", date: "11-29-2020")
event48 = Event.create(event_name: "Tyga", category: "Music", city: "San Diego", location: "Outdoor", date: "11-29-2020")
event49 = Event.create(event_name: "A Rick Ross Christmas", category: "Music", city: "Miami", location: "Outdoor", date: "12-25-2020")
event50 = Event.create(event_name: "Paul Wall", category: "Music", city: "Houston", location: "Outdoor", date: "11-21-2020")
event51 = Event.create(event_name: "Louis the Child", category: "Music", city: "Chicago", location: "Indoor", date: "11-21-2020")
event52 = Event.create(event_name: "ODESZA", category: "Musci", city: "Seattle", location: "Outdoor", date: "11-21-2020")
event53 = Event.create(event_name: "The Phantom of the Opera", category: "Theater", city: "Chicago", location: "Indoor", date: "12-25-2020")
event54 = Event.create(event_name: "The Book of Mormon", category: "Theater", city: "New York", location: "Indoor", date: "11-21-2020")
event55 = Event.create(event_name: "Aladin", category: "Theater", city: "Houston", location: "Indoor", date: "11-21-2020")
event56 = Event.create(event_name: "Cats", category: "Theater", city: "New York", location: "Indoor", date: "11-25-2020")
event57 = Event.create(event_name: "A Chorus Line", category: "Theater", city: "Miami", location: "Indoor", date: "11-29-2020")
event58 = Event.create(event_name: "Hairspray", category: "Theater", city: "Seattle", location: "Indoor", date: "11-29-2020")
event59 = Event.create(event_name: "Oklahoma", category: "Theater", city: "Milwaukee", location: "Indoor", date: "11-29-2020")
event60 = Event.create(event_name: "Annie", category: "Theater", city: "Boston", location: "Indoor", date: "11-28-2020")
event61 = Event.create(event_name: "Sound of Music", category: "Theater", city: "San Diego", location: "Indoor", date: "11-21-2020")
event62 = Event.create(event_name: "Chris Rock: LIVE!", category: "Theater", city: "Los Angeles", location: "Outdoor", date: "11-29-2020")
event63 = Event.create(event_name: "Louis C.K.", category: "Theater", city: "Chicago", location: "Indoor", date: "12-02-2020")
event64 = Event.create(event_name: "Kevin Hart: LIVE!", category: "Theater", city: "New York", location: "Indoor", date: "12-02-2020")
event65 = Event.create(event_name: "Adam Sandler: LIVE!", category: "Theater", city: "Seattle", location: "Indoor", date: "11-28-2020")
event66 = Event.create(event_name: "Ricky Gervais: LIVE!", category: "Theater", city: "San Diego", location: "Indoor", date: "11-28-2020")
event67 = Event.create(event_name: "Wanda Sykes: LIVE!", category: "Theater", city: "Houston", location: "Indoor", date: "12-25-2020")
event68 = Event.create(event_name: "Amy Poehler: LIVE!", category: "Theater", city: "Milwaukee", location: "Indoor", date: "11-28-2020")
event69 = Event.create(event_name: "Leslie Jones: LIVE!", category: "Theater", city: "Miami", location: "Indoor", date: "11-28-2020")
event70 = Event.create(event_name: "Nicole Byer: LIVE!", category: "Theater", city: "Seattle", location: "Indoor", date: "11-29-2020")


Ticket.create(user_id: user1.id, event_id: event1.id, quantity: 3)
Ticket.create(user_id: user2.id, event_id: event2.id, quantity: 1)
Ticket.create(user_id: user3.id, event_id: event3.id, quantity: 5)
Ticket.create(user_id: user4.id, event_id: event4.id, quantity: 2)
Ticket.create(user_id: user5.id, event_id: event5.id, quantity: 1)
Ticket.create(user_id: user1.id, event_id: event5.id, quantity: 3)
Ticket.create(user_id: user4.id, event_id: event1.id, quantity: 3)

